### PR TITLE
[localization] Add Turkish (tr_tr)

### PR DESCRIPTION
**Pull request by deniz-blue**
cool mod

im still unsure about the usage of ";" though, will update

### CODE REVIEW

**Comment by friedkeenan** [comment]
Thank you very much! If it would make more sense in Turkish, perhaps the semi-colon could be left out by translating the English "You may not rest now because the campfire is unlit"?

Also, when put through DeepL, the translation for `block.minecraft.campfire.rest.resting` seems to translate as "Lying in bed until the morning..." (and with Google Translate, it says "Sleeping" instead of "Lying in bed"). Are those translations correct, and if so, is there a way in Turkish to provide more distinction between "resting" and "sleeping"/"lying in bed"? Because my view of this mod is that there's not necessarily any sleeping involved when resting at a campfire, and there's certainly no bed involved. But of course, if there's not really a good way to provide that distinction in Turkish, that's perfectly fine.

**Comment by deniz-blue** [comment]
I argued with myself about it, and i dont think there's a better word for it. We have the word `dinlenmek` for resting, but its used more like `taking a break`. Could also use `mola vermek` which.. also means `taking a break`... y'know what im gonna go ask my Turkish teacher about this

**Comment by friedkeenan** [comment]
Haha, sounds good. Yeah I don't mean "resting" as "taking a break" so that wouldn't quite fit. Perhaps also it could be a translation of another phrase, like "Advancing until morning..." or something. Whatever works best.

**Comment by deniz-blue** [comment]
I found this word which works perfectly (agreed upon my friends and teacher too)

**Comment by friedkeenan** [comment]
Looks great, thank you very much

**Pull request merged**
